/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import helper.koneksi;
import helper.config;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Faa
 */
public class dataBarang extends javax.swing.JFrame {
public Connection con;
public Statement sttm;
public ResultSet rs;
public DefaultTableModel model;


    /** Creates new form dataBarang */
    public dataBarang() {
        initComponents();
        
       //Meletakkan frame di tengah layar
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
       
        int x = d.width/2 - this.getSize().width/2;
        int y = d.height/2 - this.getSize().height/2;
        
        this.setLocation(x, y); 
        
        //Memberi Nama pada Tabel
        String[] header = {"iD","Nama Barang","Harga/Item","Jumlah Stock"};
        model = new DefaultTableModel(header,0);
        Tbbarang.setModel(model);
        tampilData();
    }
    
    public void tampilData(){
        koneksi koneksi = new koneksi();
        int jumlahrow = Tbbarang.getRowCount();
        for (int n=0;n<jumlahrow;n++){
            model.removeRow(0);
        }
        
        try{
            con = koneksi.getKoneksi();
            sttm = con.createStatement();
            rs = sttm.executeQuery("SELECT * FROM data_barang");
            while(rs.next()){
                String[] row ={rs.getString(1),rs.getString(2),rs.getString(3), rs.getString(4)};
                model.addRow(row);
                
            }
            Tbbarang.setModel(model);
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
    }
    
    public void tambahData (){
        String id = ID_brg.getText();
        String nama = nama_brg.getText();
        String harga = Harga.getText();
        String stock = Stock.getText();
        
    
        koneksi koneksi = new koneksi();
        try{
            con = koneksi.getKoneksi();
            sttm = con.createStatement();
            sttm.execute("INSERT INTO data_barang VALUES('"+id+"','"+nama+"','"+harga+"','"+stock+"')");
            JOptionPane.showMessageDialog(null,"Data Berhasil Ditambahkan","Alert",JOptionPane.INFORMATION_MESSAGE);
            
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null,"Data Gagal Ditambahkan","ERROR",JOptionPane.WARNING_MESSAGE);
            System.out.println(ex.getMessage());
            
        }
    }
    public void hapus (){
        String id = ID_brg.getText();
        try{
            sttm.executeUpdate("DELETE FROM data_barang WHERE id_barang='"+id+"' ");
            JOptionPane.showMessageDialog(null, "Hapus Data Berhasil","Alert",JOptionPane.INFORMATION_MESSAGE);
            
        }catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Hapus Data Gagl", "Alert",JOptionPane.ERROR_MESSAGE);
        }
        tampilData();
    }
    
 private void clear(){
        ID_brg.setText(null);
        nama_brg.setText(null);
        Harga.setText(null);
        Stock.setText(null);

    }

        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add = new javax.swing.JLabel();
        hapus = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tbbarang = new javax.swing.JTable();
        ID_brg = new javax.swing.JTextField();
        nama_brg = new javax.swing.JTextField();
        Stock = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Harga = new javax.swing.JTextField();
        update = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button Add.png"))); // NOI18N
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 110, 50));

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.jpg"))); // NOI18N
        hapus.setEnabled(false);
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusMouseClicked(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, 50));

        Tbbarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tbbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tbbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbbarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tbbarang);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 680, 150));

        ID_brg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_brgActionPerformed(evt);
            }
        });
        getContentPane().add(ID_brg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 200, 30));
        getContentPane().add(nama_brg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 252, 200, 30));
        getContentPane().add(Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 190, 30));

        jLabel7.setText("ID Barang");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 30));

        jLabel8.setText("Nama Barang");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 30));

        jLabel9.setText("Stock ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 70, 30));
        getContentPane().add(Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 190, 30));

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button update.png"))); // NOI18N
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, -1, -1));

        jLabel10.setText("Harga/item");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 70, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 690, 180));

        close.setBackground(new java.awt.Color(186, 17, 48));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("X");
        close.add(jLabel6);

        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/data barang.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // memasukkan data ke dalam tabel dan database
       tambahData();
       tampilData();
       clear ();
    }//GEN-LAST:event_addMouseClicked

    private void hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseClicked
        // hapus data dari database
        hapus();

    }//GEN-LAST:event_hapusMouseClicked

    private void ID_brgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_brgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_brgActionPerformed

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // update data
       try{
            String sql ="INSERT data_barang set id_barang ='"+ID_brg.getText()
                    +"' ,nama_barang = '"+nama_brg.getText()
                    +"' ,harga_barang ='"+Harga.getText()
                    +"' ,jumlah_stock ='"+Stock.getText()
                    +"' On Duplicate Key Update id_barang = '"+ID_brg.getText()+"' ,nama_barang = '"+nama_brg.getText() +"' ,harga_barang ='"+Harga.getText()+"' ,jumlah_stock ='"+Stock.getText()
                      
                    +"'";
            java.sql.Connection conn = (Connection)config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data Berhasil Di Update");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Data Gagal Di Update");
             System.out.println(e.getMessage());
        }
        tampilData();
  

    }//GEN-LAST:event_updateMouseClicked

    private void TbbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbbarangMouseClicked
        // TODO add your handling code here:
        int row = Tbbarang.getSelectedRow();
        hapus.setEnabled(true);

        String id = Tbbarang.getValueAt(row, 0).toString();
        String nama = Tbbarang.getValueAt(row, 1).toString();
        String harga = Tbbarang.getValueAt(row, 2).toString();
        String stock = Tbbarang.getValueAt(row, 3).toString();
        
        ID_brg.setText(id);
        nama_brg.setText(nama);
        Harga.setText(harga);
        Stock.setText(stock);
        
    }//GEN-LAST:event_TbbarangMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        menuAdmin start = new menuAdmin ();
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Harga;
    private javax.swing.JTextField ID_brg;
    private javax.swing.JTextField Stock;
    private javax.swing.JTable Tbbarang;
    private javax.swing.JLabel add;
    private javax.swing.JPanel close;
    private javax.swing.JLabel hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nama_brg;
    private javax.swing.JLabel update;
    // End of variables declaration//GEN-END:variables

}
