/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Faa
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
        //Meletakkan frame di tengah layar
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
       
        int x = d.width/2 - this.getSize().width/2;
        int y = d.height/2 - this.getSize().height/2;
        
        this.setLocation(x, y); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tombolGuru = new javax.swing.JLabel();
        buttonMurid = new javax.swing.JLabel();
        Frame = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tombolGuru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button teacher.png"))); // NOI18N
        tombolGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolGuruMouseClicked(evt);
            }
        });
        getContentPane().add(tombolGuru, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 405, -1, 50));

        buttonMurid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/button student.png"))); // NOI18N
        buttonMurid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMuridMouseClicked(evt);
            }
        });
        getContentPane().add(buttonMurid, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, -1, -1));

        Frame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/login.jpg"))); // NOI18N
        getContentPane().add(Frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 740, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMuridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMuridMouseClicked
        // ke frame Form siswa
         loginStudent start = new loginStudent ();
         start.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_buttonMuridMouseClicked

    private void tombolGuruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolGuruMouseClicked
        // ke menu login guru
         loginTeacher start = new loginTeacher ();
         start.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_tombolGuruMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Frame;
    private javax.swing.JLabel buttonMurid;
    private javax.swing.JLabel tombolGuru;
    // End of variables declaration//GEN-END:variables
}
